name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest          # 使用最新的 ubuntu
    steps:
      - uses: actions/checkout@v2   # 下載 master 最新的程式碼
      - uses: actions/setup-node@v1 # 安裝 node
      - run: npm i -g yarn
      - run: yarn install
      - run: yarn run deploy
